### ISSUE TITLE
Do not allow for multiple transactions in the mempool spending the same box

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#1165]

**Comment by jasondavies** [comment]
Why shouldn't this be allowed?

**Comment by kushti** [comment]
@jasondavies I think it is about easier DDoS possibility in the first place? For example, if I have 10 outputs, I can create and send to the network 10!=3.6M spending transactions by reordering the inputs, with double spending prevention just 10. 

Other arguments would be more nuanced likely )

**Comment by aslesarenko** [comment]
@kushti I think it would be useful to extend the behavior of transaction send method to somehow communicate to the application, that sending was rejected due to double spending.
Such kind of feedback will be useful for multistage contracts with alternative spending paths.
If I send a transaction using PathA, I may receive rejection from the pool that there is already a transaction spending the same box by following PathB. 

Simple RejectionReason.DoubleSpending will be enough for the application.

**Comment by kushti** [comment]
> @kushti I think it would be useful to extend the behavior of transaction send method to somehow communicate to the application, that sending was rejected due to double spending.
> Such kind of feedback will be useful for multistage contracts with alternative spending paths.
> If I send a transaction using PathA, I may receive rejection from the pool that there is already a transaction spending the same box by following PathB.
> 
> Simple RejectionReason.DoubleSpending will be enough for the application.

You mean HTTP API? Transaction is being sent to the mempool asynchronously there, after validation, so mempool response is not known even know,

**Comment by aslesarenko** [comment]
Yeah, I mean HTTP API. Ok, if it not easy to do now, maybe just keep in mind for the future.

**Comment by scalahub** [comment]
Would this allow us to double spend with higher fee (RBF)? This is needed as a tx is often stuck due to low fee

**Comment by kushti** [comment]
> Would this allow us to double spend with higher fee (RBF)? This is needed as a tx is often stuck due to low fee

Yes, RBF is done
