### ISSUE TITLE
Internal error from node in testnet

### ISSUE THREAD

**Issue by neal-zhu** [ergoplatform/ergo#1275]
Hi guys：

  I got periodic internal errors from /mining/candidate interface.
There are some WARN log in ergo.log which said:
`18:23:47.940 WARN  [tor.default-dispatcher-15] s.c.n.NetworkController - Connection to peer /213.239.193.208:9020 is already established`

How can I fix it ?

**Comment by kushti** [comment]
@neal-zhu how often do you poll the /mining/candidate

In upcoming 4.0.3 version a detailed message will be provided.



18:23:47.940 WARN [tor.default-dispatcher-15] s.c.n.NetworkController - Connection to peer /213.239.193.208:9020 is already established 

is not related to mining logic. It is corresponding to P2P layer, not problematic in general and will be fixed in future versions.

**Comment by neal-zhu** [comment]
We call /mining/candidate every 100ms, maybe that is too ofen?

**Comment by kushti** [comment]
@neal-zhu it is good. Please try 4.0.3 it is providing error details
