### ISSUE TITLE
Strictly require asset and ergo amounts in a box to be positive

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#378]
Currently we require asset and ergo amounts in a box to be non-negative. For assets at least this does not make much sense probably. Consider this in testnet2.

**Comment by catena2w** [comment]
For ergo i might be useful to have boxes with assets only, without any ergo inside

**Comment by kushti** [comment]
@catena2w @oskin1 because of the storage fee, we can require that a new box should contain enough to be collected (in the extreme, it should contain storage fee for all the period at least). Finally, I have a rule skipped in the storage fee instantiation.

With zero-value outputs we have a possible problem though. Miners could be okay with creation of zero-value dust if creating transaction is paying enough, but then the dust will live forever (as a miner has no incentive to collect it).

**Comment by catena2w** [comment]
Few notes after discussion:
- Requiring just `box.value > 0` does not make sense, as soon as `10^(-9) Ergo` is not an incentive for miners to remove a dust.
- Problem with the incentive to collect dust may be fixed by a smart contract, that pays some coins to miners, that collect dust. This contract, however, will have non-zero cost that may be a problem, if there is some free space in a block, but computation limit is reached.
- Some minimal box value `MinBoxAmount` may be included in a consensus protocol and can be changed by miner votes.

**Comment by catena2w** [comment]
Fixed via minimal box value parameter that may be changed via voting
