### ISSUE TITLE
dead letters

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#480]
Sometimes there are dead letters in logs (and in tests). We should fix them.

**Comment by oskin1** [comment]
@catena2w, all dead letters in tests are caused by working with NodeViewHolder actor from ErgoMinerSpec which is not an actor, so all messages from NVH goes to DeadLetters. I think it is normal behavior if we use such approach.
https://github.com/ergoplatform/ergo/blob/2789648afccb0721b48e3d8d46ccde65884a109a/src/test/scala/org/ergoplatform/mining/ErgoMinerSpec.scala#L103

**Comment by oskin1** [comment]
https://github.com/ScorexFoundation/Scorex/issues/316

**Comment by catena2w** [comment]
Ergo part is fixed in https://github.com/ergoplatform/ergo/pull/492
