### ISSUE TITLE
Network layer

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/ergo#583]
- [ ] Blacklisting
- [x] Versioning
- [x] Mod signaling
- [x] Sync Info

**Comment by catena2w** [comment]
Blacklisting will be implemented by @oskin1 in https://github.com/ScorexFoundation/Scorex/issues/177.
Mod signaling will be implemented by @kushti in https://github.com/ergoplatform/ergo/issues/623

**Comment by catena2w** [comment]
# Proposals for messages changes:

Message: 
- take `Magic bytes` from config, to distinguish different networks (testnet/mainnet)
- checksum is probably useless, as far as tcp packets already have it. + calculate Blake2b256 and take 4 bytes from it is too resource consuming, we may just calculate Blake with 4 bytes output size

Handshake: 
- fill features (in #623)
- add version, set connection version as the lowest version of 2 peers, send only messages that are supported by this version to each other;
- Possibly add nonce and current height (may be added in next protocol versions)

GetPeers/Peers:
- add timestamp when peer was last seen.
- remove peer from peer list if it was not seen for some time (e.g. 3 hours)
- do respond with peers that are in list but are not connected

Inv:
- Bitcoin node limit is 50000, that is much higher than our 500

RequestModifier:
- We now require that all modifiers have the same type. It might be useful to allow modifiers to have different types (e.g. requesting all block sections of one header in one request). Bitcoin allows to request different modifier types

ErgoSyncInfo:
- make sparse ids, like Bitcoin - ids are ordered, newest back to genesis block (dense to start, but then sparse).

Messages that are implemented in Bitcoin protocol and may be useful in the future, but are not necessary right now:
- mempool
- notfound
- reject
- feefilter
- HeaderAndShortIDs, BlockTransactions, filter*

**Comment by oskin1** [comment]
Possible misbehavior options for peer to be blacklisted:

PermanentBan:

- Message from peer failed to be deserialized (e.g. Handshake parsing)

MisbehaviorBan (12h default, adjustable in settings):

- Persistent modifier from peer turned out to be Semantically or Syntactically invalid
- Transaction broadcasted by peer immediately fails at first validation (when a transaction became invalid (outdated) afterwards sender should not be banned)

SpamBan (10min default, adjustable in settings):
- Peer sent non requested modifier
