### ISSUE TITLE
Inefficient difficulty check

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#872]
Currently, *requiredDifficultyAfter* in *HeadersProcessor* doing complete re-calculation for each block based on previous epochs. Though all the headers are probably cached to this moment, so no excessive reads from database, still, this is very inefficient way. Difficulty recalculation should use cached epoch difficulties.

Help wanted!

Bonus: 200 Ergs

**Comment by knizhnik** [comment]
I do not completely understand how to simulate workload on which HeadersProcessor becomes a bottleneck. I tried to start new node according at my desktop. Synchronization of node takes substantial amount of time (several minutes), bust most of the time CPU usage is zero. Looks like it is waiting for receiving some data from network.

Only once I was able to catch the moment when application is actually doing something:
`nonEmpty:114, TraversableOnce (scala.collection)
nonEmpty$:114, TraversableOnce (scala.collection)
nonEmpty:108, AbstractTraversable (scala.collection)
loop$1:55, Growable (scala.collection.generic)
$plus$plus$eq:61, Growable (scala.collection.generic)
$plus$plus$eq$:53, Growable (scala.collection.generic)
$plus$plus$eq:184, ListBuffer (scala.collection.mutable)
$plus$plus$eq:47, ListBuffer (scala.collection.mutable)
$colon$plus:568, SeqLike (scala.collection)
$colon$plus$:566, SeqLike (scala.collection)
$colon$plus:45, AbstractSeq (scala.collection)
loop$1:198, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
headerChainBack:210, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
headerChainBack$:190, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
headerChainBack:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
requiredDifficultyAfter:252, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
requiredDifficultyAfter$:241, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
requiredDifficultyAfter:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
$anonfun$validateChildBlockHeader$5:293, HeadersProcessor$HeaderValidator (org.ergoplatform.nodeView.history.storage.modifierprocessors)
apply:-1, HeadersProcessor$HeaderValidator$$Lambda$1505 (org.ergoplatform.nodeView.history.storage.modifierprocessors)
$anonfun$validateEquals$1:105, ValidationState (scorex.core.validation)
apply:-1, ValidationState$$Lambda$1444 (scorex.core.validation)
pass:72, ValidationState (scorex.core.validation)
validateEquals:105, ValidationState (scorex.core.validation)
validateChildBlockHeader:293, HeadersProcessor$HeaderValidator (org.ergoplatform.nodeView.history.storage.modifierprocessors)
$anonfun$validate$1:268, HeadersProcessor$HeaderValidator (org.ergoplatform.nodeView.history.storage.modifierprocessors)
apply:-1, HeadersProcessor$HeaderValidator$$Lambda$1412 (org.ergoplatform.nodeView.history.storage.modifierprocessors)
map:230, Option (scala)
validate:267, HeadersProcessor$HeaderValidator (org.ergoplatform.nodeView.history.storage.modifierprocessors)
validate:158, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
validate$:158, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
validate:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
applicableTry:214, ErgoHistoryReader (org.ergoplatform.nodeView.history)
applicableTry$:211, ErgoHistoryReader (org.ergoplatform.nodeView.history)
applicableTry:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
tryToApply$1:16, ErgoModifiersCache (org.ergoplatform.nodeView)
$anonfun$findCandidateKey$9:41, ErgoModifiersCache (org.ergoplatform.nodeView)
$anonfun$findCandidateKey$9$adapted:38, ErgoModifiersCache (org.ergoplatform.nodeView)
apply:-1, ErgoModifiersCache$$Lambda$1463 (org.ergoplatform.nodeView)
find:993, Iterator (scala.collection)
find$:990, Iterator (scala.collection)
find:1429, AbstractIterator (scala.collection)
find:81, IterableLike (scala.collection)
find$:80, IterableLike (scala.collection)
find:56, AbstractIterable (scala.collection)
$anonfun$findCandidateKey$8:38, ErgoModifiersCache (org.ergoplatform.nodeView)
apply:-1, ErgoModifiersCache$$Lambda$1462 (org.ergoplatform.nodeView)
orElse:447, Option (scala)
findCandidateKey:43, ErgoModifiersCache (org.ergoplatform.nodeView)
findCandidateKey:11, ErgoModifiersCache (org.ergoplatform.nodeView)
popCandidate:76, ModifiersCache (scorex.core)
popCandidate$:75, ModifiersCache (scorex.core)
popCandidate:110, DefaultModifiersCache (scorex.core)
applyLoop$1:326, NodeViewHolder$$anonfun$processRemoteModifiers$1 (scorex.core)
applyOrElse:335, NodeViewHolder$$anonfun$processRemoteModifiers$1 (scorex.core)
applyOrElse:175, PartialFunction$OrElse (scala)
aroundReceive:539, Actor (akka.actor)
aroundReceive$:537, Actor (akka.actor)
aroundReceive:23, ErgoNodeViewHolder (org.ergoplatform.nodeView)
receiveMessage:612, ActorCell (akka.actor)
invoke:581, ActorCell (akka.actor)
processMailbox:268, Mailbox (akka.dispatch)
run:229, Mailbox (akka.dispatch)
exec:241, Mailbox (akka.dispatch)
doExec:260, ForkJoinTask (akka.dispatch.forkjoin)
runTask:1339, ForkJoinPool$WorkQueue (akka.dispatch.forkjoin)
runWorker:1979, ForkJoinPool (akka.dispatch.forkjoin)
run:107, ForkJoinWorkerThread (akka.dispatch.forkjoin)`

So if I correctly interpret this code, it is in sequence :+ method:

`            loop(parent, acc :+ parent)
`
This method always creates copy of the sequence, so if number of inserted elements is large, it will have quadratic complexity and be very inefficient. May be it is better to rewrite loop() method without recursion and use in-place append method for adding elements?

**Comment by knizhnik** [comment]
Once I was able to obtain stack when database is accessed:

`Get:-1, NativeDB$DBJNI (org.fusesource.leveldbjni.internal)
get:307, NativeDB (org.fusesource.leveldbjni.internal)
get:300, NativeDB (org.fusesource.leveldbjni.internal)
get:293, NativeDB (org.fusesource.leveldbjni.internal)
get:85, JniDB (org.fusesource.leveldbjni.internal)
get:77, JniDB (org.fusesource.leveldbjni.internal)
get:15, KVStore (org.ergoplatform.db)
get$:14, KVStore (org.ergoplatform.db)
get:8, LDBKVStore (org.ergoplatform.db)
contains:59, HistoryStorage (org.ergoplatform.nodeView.history.storage)
contains:76, ErgoHistoryReader (org.ergoplatform.nodeView.history)
contains$:76, ErgoHistoryReader (org.ergoplatform.nodeView.history)
contains:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
isSemanticallyValid:297, ErgoHistoryReader (org.ergoplatform.nodeView.history)
isSemanticallyValid$:293, ErgoHistoryReader (org.ergoplatform.nodeView.history)
isSemanticallyValid:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
modifierById:59, ErgoHistoryReader (org.ergoplatform.nodeView.history)
modifierById$:58, ErgoHistoryReader (org.ergoplatform.nodeView.history)
modifierById:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
typedModifierById:71, ErgoHistoryReader (org.ergoplatform.nodeView.history)
typedModifierById$:71, ErgoHistoryReader (org.ergoplatform.nodeView.history)
typedModifierById:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
loop$1:196, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
headerChainBack:210, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
headerChainBack$:190, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
headerChainBack:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
requiredDifficultyAfter:252, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
requiredDifficultyAfter$:241, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
requiredDifficultyAfter:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
$anonfun$validateChildBlockHeader$5:293, HeadersProcessor$HeaderValidator (org.ergoplatform.nodeView.history.storage.modifierprocessors)
apply:-1, HeadersProcessor$HeaderValidator$$Lambda$1505 (org.ergoplatform.nodeView.history.storage.modifierprocessors)
$anonfun$validateEquals$1:105, ValidationState (scorex.core.validation)
apply:-1, ValidationState$$Lambda$1444 (scorex.core.validation)
pass:72, ValidationState (scorex.core.validation)
validateEquals:105, ValidationState (scorex.core.validation)
validateChildBlockHeader:293, HeadersProcessor$HeaderValidator (org.ergoplatform.nodeView.history.storage.modifierprocessors)
$anonfun$validate$1:268, HeadersProcessor$HeaderValidator (org.ergoplatform.nodeView.history.storage.modifierprocessors)
apply:-1, HeadersProcessor$HeaderValidator$$Lambda$1412 (org.ergoplatform.nodeView.history.storage.modifierprocessors)
map:230, Option (scala)
validate:267, HeadersProcessor$HeaderValidator (org.ergoplatform.nodeView.history.storage.modifierprocessors)
validate:158, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
validate$:158, HeadersProcessor (org.ergoplatform.nodeView.history.storage.modifierprocessors)
validate:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
applicableTry:214, ErgoHistoryReader (org.ergoplatform.nodeView.history)
applicableTry$:211, ErgoHistoryReader (org.ergoplatform.nodeView.history)
applicableTry:242, ErgoHistory$$anon$3 (org.ergoplatform.nodeView.history)
tryToApply$1:16, ErgoModifiersCache (org.ergoplatform.nodeView)
$anonfun$findCandidateKey$9:41, ErgoModifiersCache (org.ergoplatform.nodeView)
$anonfun$findCandidateKey$9$adapted:38, ErgoModifiersCache (org.ergoplatform.nodeView)
apply:-1, ErgoModifiersCache$$Lambda$1463 (org.ergoplatform.nodeView)
find:993, Iterator (scala.collection)
find$:990, Iterator (scala.collection)
find:1429, AbstractIterator (scala.collection)
find:81, IterableLike (scala.collection)
find$:80, IterableLike (scala.collection)
find:56, AbstractIterable (scala.collection)
$anonfun$findCandidateKey$8:38, ErgoModifiersCache (org.ergoplatform.nodeView)
apply:-1, ErgoModifiersCache$$Lambda$1462 (org.ergoplatform.nodeView)
orElse:447, Option (scala)
findCandidateKey:43, ErgoModifiersCache (org.ergoplatform.nodeView)
findCandidateKey:11, ErgoModifiersCache (org.ergoplatform.nodeView)
popCandidate:76, ModifiersCache (scorex.core)
popCandidate$:75, ModifiersCache (scorex.core)
popCandidate:110, DefaultModifiersCache (scorex.core)
applyLoop$1:326, NodeViewHolder$$anonfun$processRemoteModifiers$1 (scorex.core)
applyOrElse:335, NodeViewHolder$$anonfun$processRemoteModifiers$1 (scorex.core)
applyOrElse:175, PartialFunction$OrElse (scala)
aroundReceive:539, Actor (akka.actor)
aroundReceive$:537, Actor (akka.actor)
aroundReceive:23, ErgoNodeViewHolder (org.ergoplatform.nodeView)
receiveMessage:612, ActorCell (akka.actor)
invoke:581, ActorCell (akka.actor)
processMailbox:268, Mailbox (akka.dispatch)
run:229, Mailbox (akka.dispatch)
exec:241, Mailbox (akka.dispatch)
doExec:260, ForkJoinTask (akka.dispatch.forkjoin)
runTask:1339, ForkJoinPool$WorkQueue (akka.dispatch.forkjoin)
runWorker:1979, ForkJoinPool (akka.dispatch.forkjoin)
run:107, ForkJoinWorkerThread (akka.dispatch.forkjoin)`


This access is caused by access() method in isSemanticallyValid method:
`override def isSemanticallyValid(modifierId: ModifierId): ModifierSemanticValidity = {
    historyStorage.getIndex(validityKey(modifierId)) match {
      case Some(b) if b.headOption.contains(1.toByte) => ModifierSemanticValidity.Valid
      case Some(b) if b.headOption.contains(0.toByte) => ModifierSemanticValidity.Invalid
      case None if contains(modifierId) => ModifierSemanticValidity.Unknown
      case None => ModifierSemanticValidity.Absent
      case m =>
        log.error(s"Incorrect validity status: $m")
        ModifierSemanticValidity.Absent
    }
  }
`

As far as I understand, historyStorage is actually local cache used to minimize accesses to the storage.  I wonder if we can also store negative entries in it (ModifierSemanticValidity.Absent/Uknown cases).

**Comment by glasgowm148** [comment]
closed with #1190 ?

**Comment by kushti** [comment]
Fixed in nipopow-bootstrapping branch, now headerChainBack is used only when difficulty for non-best chain header is checked (probability of that is normally low)
