### ISSUE TITLE
[API] Specify secrets while creating transaction

### ISSUE THREAD

**Issue by scalahub** [ergoplatform/ergo#940]
In ErgoMix, for example, we require that certain public keys are used only once. In particular, security is lost if Bob uses the same public key in any other transaction. Thus, Bob's public key in the mix-step can be used only once. (the leak does not require spending from the reused key. Just using it to receive funds reveals the secret bit b).

Current API does not allow us to use arbitrary secrets to sign transactions. Rather it uses existing private keys as secrets. If we let Bob use these secrets in mixing, then the wallet *may* reuse the address in a different transaction. 

Hence, ideally, we should not be required to use secrets generated via the wallet. Rather we should be allowed to use arbitrary secrets generated outside the wallet.

One way to do this would be to extend the /wallet/transaction/generate by adding yet another array:

	{
	  "requests": [...],
	  "fee": 1000000,
	  "inputsRaw": [
	    "1a2b", "2b3c"
	  ],
          ...
	  "secrets": ["12314", "4567"]
	}

Perhaps secrets are better encoded in hex? I presume they are always BigInts.

**Comment by kushti** [comment]
Secrets are big ints (mod q) indeed, how signer should use them though?

**Comment by scalahub** [comment]
I think it should be done in "use and forget" mode.

**Comment by jasondavies** [comment]
I think Bob has to use their secret twice: once to create the full mix box, and then again to spend their output?

**Comment by jasondavies** [comment]
I've implemented a much more general transaction signing API that takes a full unsigned transaction and attempts to sign it.  The resulting signed transaction can then be POSTed to /transactions to broadcast it.  The reason is that I wanted to select the boxes to spend myself.

This API doesn't even really need a wallet (though ideally it should still use wallet secrets if available).  I'm now working on encoding secrets to be sent with the transaction for signing (currently just hard coded).

Of course, it's not really ideal to send secrets via the API due to the possibility of eavesdropping, but in ErgoMix, Bob needs access to their secret to calculate g^xy.
