### ISSUE TITLE
Check the node on Raspberry Pi or similar constrained device

### ISSUE THREAD

**Issue by kushti** [ergoplatform/ergo#972]
Check whether it is possible the node on Raspberry Pi or similar constrained device (with 1 GB RAM at least) and write a manual on how to do that,

**Comment by filippounits** [comment]
I've checked the node on a Raspberry Pi 3 Model B with 1Gb RAM. This is the hardware, software and the error/warn.

Version of Debian:
`pi@raspberrypi:~ $ cat /etc/debian_version
9.11`

OS Release Notes:
`pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

Kernel Version:
`pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l GNU/Linux`

Hardware Version:
`pi@raspberrypi:~ $ cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a22082
Serial		: 00000000f3d5539d`


ERROR Reported:
`WARN  [ctor.default-dispatcher-5] scorex.db.LDBFactory$ - Failed to load database factory org.fusesource.leveldbjni.JniDBFactory due to: {}
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni32-3.2.0 in java.library.path, no leveldbjni-3.2.0 in java.library.path, no leveldbjni in java.library.path, /tmp/libleveldbjni-32-3-910582559771341055.2: /tmp/libleveldbjni-32-3-910582559771341055.2: cannot open shared object file: No such file or directory (Possible cause: can't load IA 32-bit .so on a ARM-bit platform)]
`

**Comment by kushti** [comment]
Corresponding issue: #1038

**Comment by filippounits** [comment]
So, the new (still private ATM) version of the node 3.2.1 was fully synced in the raspy with the "light" node using this .conf https://gist.github.com/kushti/1b9434e12b051a2db5b22e62a8d85cdb!

Here some details:

Version of Debian:
```
pi@raspberrypi:~ $ cat /etc/debian_version
10.2
```
Java Version:
```
pi@raspberrypi:~ $ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Raspbian-1deb10u1)
OpenJDK Server VM (build 11.0.6+10-post-Raspbian-1deb10u1, mixed mode)
```
OS Release:
```
pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
Kernel Version:
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.19.93-v7+ #1290 SMP Fri Jan 10 16:39:50 GMT 2020 armv7l GNU/Linux
```
Hardware is the same.

https://twitter.com/FilippoUnits/status/1223156793473454080
